### ISSUE TITLE
User Flows

### ISSUE THREAD

**Issue by 2manslkh** [Laminar-Finance/.github#5]

**Comment by dominicacodes** [comment]
Hey Kenk can you describe to me what the user flow looks like from the perspective of the business that is using it?

**Comment by 2manslkh** [comment]
User Entering a SuperGym:

Pre-condtion
- user has a metamask mobile wallet
- user has some sUSDT in their wallet

Flow:
- user walks into a SuperGym
- user sees the gate to the gym, attached to it is a screen prompting the user to connect their wallet to it.
- user opens up their metamask mobile wallet and launches the QR code scanner to scan the wallet connect QR code on the gate's screen.
- user signs a message on their metamask mobile and is now connected to the SuperGates webapp.
- user sees that the SuperGates webapp attached to the gate has changed to the next screen, which prompts the user to check-in.
- user presses the check-in button and sees that a message to approve the check-in transaction had appeared on their metamask mobile wallet.
- user signs the message on the mobile wallet.
- the gate opens
- the user walks into the gym area and begins their workout.
